import type { ArtifactDocument, Card, Layer, TextLayer, ShapeLayer, OverlayLayer } from '@orra/shared';
import { ArtifactDocumentSchema } from '@orra/shared';

// ---------------------------------------------------------------------------
// Mock artifact generator
// ---------------------------------------------------------------------------
// Phase 9H: produces a deterministic, valid ArtifactDocument using only
// text, shape, overlay, and baseColor layers. No external image assets.
//
// The output is visually simple but schema-valid:
//   - one gradient overlay (bottom scrim)
//   - one shape accent
//   - one title text layer
//   - one body text layer
//   - optional per-card index text for carousels
//
// All fonts come from the shared catalog. No AI, no R2, no provider calls.

export interface MockGenerationInput {
  /** The current artifact document to build upon. */
  currentDocument: ArtifactDocument;
  /** Number of cards to produce. For posts this is 1. For carousels it
   *  comes from the approval plan or defaults to the current card count
   *  (minimum 3 if the document has only 1 empty card). */
  targetCardCount?: number;
  /** Optional topic extracted from the approval plan for mock copy. */
  topic?: string | null;
}

const ORRA_PALETTE = ['#1d2a30', '#354e53', '#5e7680', '#a4b7bd', '#c8d1d8'];

const TITLE_FONT = 'Newsreader';
const BODY_FONT = 'Inter';
const ACCENT_FONT = 'Space Grotesk';

function pickBaseColor(index: number): string {
  return ORRA_PALETTE[index % ORRA_PALETTE.length];
}

function randomUUID(): string {
  return crypto.randomUUID();
}

function makeOverlayLayer(z: number, cardH: number): OverlayLayer {
  return {
    id: randomUUID(),
    type: 'overlay',
    z,
    x: 0,
    y: Math.round(cardH * 0.55),
    w: 1080,
    h: Math.round(cardH * 0.45),
    rotation: 0,
    opacity: 0.35,
    locked: false,
    hidden: false,
    overlayKind: 'linearGradient',
    params: {
      stops: [
        { offset: 0, color: '#1d2a30' },
        { offset: 1, color: '#354e53' },
      ],
      angle: 180,
    },
  };
}

function makeShapeAccent(z: number): ShapeLayer {
  return {
    id: randomUUID(),
    type: 'shape',
    z,
    x: 60,
    y: 60,
    w: 80,
    h: 6,
    rotation: 0,
    opacity: 0.9,
    locked: false,
    hidden: false,
    shapeKind: 'rect',
    fill: '#a4b7bd',
    cornerRadius: 3,
  };
}

function makeTitleText(z: number, cardW: number, topic?: string | null): TextLayer {
  const content = topic ? `Mock: ${topic}` : 'Mock Generation';
  return {
    id: randomUUID(),
    type: 'text',
    z,
    x: 60,
    y: 140,
    w: cardW - 120,
    h: 200,
    rotation: 0,
    opacity: 1,
    locked: false,
    hidden: false,
    content,
    fontFamily: TITLE_FONT,
    fontSize: 72,
    fontWeight: 400,
    lineHeight: 1.15,
    letterSpacing: 0,
    color: '#c8d1d8',
    align: 'left',
    role: 'title',
  };
}

function makeBodyText(z: number, cardW: number): TextLayer {
  return {
    id: randomUUID(),
    type: 'text',
    z,
    x: 60,
    y: 380,
    w: cardW - 120,
    h: 300,
    rotation: 0,
    opacity: 0.85,
    locked: false,
    hidden: false,
    content: 'This is a placeholder generated by the mock consumer. No AI or image assets were used. Text remains fully editable.',
    fontFamily: BODY_FONT,
    fontSize: 24,
    fontWeight: 400,
    lineHeight: 1.5,
    letterSpacing: 0.2,
    color: '#a4b7bd',
    align: 'left',
    role: 'body',
  };
}

function makeIndexText(z: number, cardW: number, cardH: number, index: number, total: number): TextLayer {
  return {
    id: randomUUID(),
    type: 'text',
    z,
    x: cardW - 120,
    y: cardH - 80,
    w: 100,
    h: 40,
    rotation: 0,
    opacity: 0.6,
    locked: false,
    hidden: false,
    content: `${index + 1} / ${total}`,
    fontFamily: ACCENT_FONT,
    fontSize: 18,
    fontWeight: 500,
    lineHeight: 1.2,
    letterSpacing: 1,
    color: '#c8d1d8',
    align: 'right',
    role: 'caption',
  };
}

function buildMockCard(index: number, total: number, ratioW: number, ratioH: number, topic?: string | null): Card {
  const layers: Layer[] = [];

  // z=0: gradient overlay scrim at bottom
  layers.push(makeOverlayLayer(0, ratioH));

  // z=1: shape accent bar
  layers.push(makeShapeAccent(1));

  // z=2: title text
  layers.push(makeTitleText(2, ratioW, topic));

  // z=3: body text
  layers.push(makeBodyText(3, ratioW));

  // z=4: index text only for carousel with >1 card
  if (total > 1) {
    layers.push(makeIndexText(4, ratioW, ratioH, index, total));
  }

  return {
    id: randomUUID(),
    index,
    baseColor: pickBaseColor(index),
    layers,
  };
}

/**
 * Produce a deterministic mock ArtifactDocument update.
 *
 * Rules:
 * - Preserves artifactId, type, ratio.
 * - Increments document.version by 1.
 * - Produces the target number of cards (default: keep current count, min 3 for carousel).
 * - Only text, shape, overlay layers. No image-backed layers.
 * - All fonts are catalog-valid.
 */
export function generateMockArtifactDocument(input: MockGenerationInput): ArtifactDocument {
  const doc = input.currentDocument;

  const isCarousel = doc.type === 'carousel';
  const currentCount = doc.cards.length;

  let targetCount: number;
  if (input.targetCardCount !== undefined && input.targetCardCount > 0) {
    targetCount = input.targetCardCount;
  } else if (isCarousel) {
    targetCount = Math.max(currentCount, 3);
  } else {
    targetCount = 1;
  }

  const cards: Card[] = [];
  for (let i = 0; i < targetCount; i++) {
    cards.push(buildMockCard(i, targetCount, doc.ratio.w, doc.ratio.h, input.topic));
  }

  const generated: ArtifactDocument = {
    schemaVersion: doc.schemaVersion,
    artifactId: doc.artifactId,
    type: doc.type,
    ratio: doc.ratio,
    cards,
    version: doc.version + 1,
  };

  // Defensive validation: if this fails, the generator has a bug.
  const parsed = ArtifactDocumentSchema.safeParse(generated);
  if (!parsed.success) {
    const issues = parsed.error.issues.map((issue: { path: (string | number)[]; message: string }) => `${issue.path.join('.')}: ${issue.message}`).join('; ');
    throw new Error(`Mock artifact document failed validation: ${issues}`);
  }

  return parsed.data;
}
