import type { AIProvider, TextPlanRequest, TextPlanResult, ImageGenerationRequest, ImageGenerationResult } from '../types.js';

// ---------------------------------------------------------------------------
// Fake AI provider
// ---------------------------------------------------------------------------
// Phase 13A: deterministic, no network calls. Replicates the topic-parsing
// logic that previously lived inline in mockGenerationConsumer. Produces the
// same output as before; no visible change to generated artifacts.
//
// Real providers replace this in Phase 13B/13C.

export class FakeAIProvider implements AIProvider {
  readonly name = 'fake' as const;

  async planText(input: TextPlanRequest): Promise<TextPlanResult> {
    const raw = input.approvalCard?.summaryLine ?? input.prompt;
    const title = raw.replace(/^Ready to create\s*(a\s*)?/i, '').trim() || 'design';
    const cardCount = input.projectType === 'carousel' ? 3 : 1;

    const styleNotes: string[] = [];
    if (input.brandContext) {
      if (input.brandContext.tone) {
        styleNotes.push(`tone: ${input.brandContext.tone}`);
      }
      if (input.brandContext.visualDirection) {
        styleNotes.push(`style: ${input.brandContext.visualDirection}`);
      }
    }

    return {
      summary: raw,
      cardCount,
      title,
      body: 'This is a placeholder generated by the mock consumer. No AI or image assets were used. Text remains fully editable.',
      styleNotes,
    };
  }

  async generateImageOrDocument(_input: ImageGenerationRequest): Promise<ImageGenerationResult> {
    return { kind: 'mock_document' };
  }
}
