import type { ImageProvider, ImageGenerationRequest, ImageGenerationResult, ImageEditRequest } from '../imageTypes.js';
import { AIProviderError } from '../errors.js';
import type { AIProviderObserver } from '../observability.js';
import { NoopAIProviderObserver } from '../observability.js';

// ---------------------------------------------------------------------------
// FLUX image provider — Phase 15B
// ---------------------------------------------------------------------------
// Targets Black Forest Labs FLUX Schnell via the BFL REST API.
// Two-step async flow: submit job → poll → fetch image bytes.
// All three network calls go through the injectable fetch for test isolation.
// No generated bytes are stored; callers receive raw Uint8Array in memory only.
// Generated image R2 storage and artifact integration come in later phases.

const DEFAULT_BASE_URL = 'https://api.bfl.ml';
const DEFAULT_MODEL = 'flux-schnell';
const DEFAULT_TIMEOUT_MS = 60_000;
const DEFAULT_MAX_POLL_ATTEMPTS = 20;
const DEFAULT_POLL_INTERVAL_MS = 2_000;

export interface FluxImageProviderConfig {
  apiKey: string;
  baseUrl?: string;
  model?: string;
  timeoutMs?: number;
  maxPollAttempts?: number;
  pollIntervalMs?: number;
  observer?: AIProviderObserver;
  /** Injectable fetch — defaults to globalThis.fetch. Tests must supply a mock. */
  fetch?: typeof globalThis.fetch;
  /** Injectable sleep — defaults to setTimeout-based delay. Tests supply async () => {}. */
  sleep?: (ms: number) => Promise<void>;
}

// ---------------------------------------------------------------------------
// Internal BFL response shape guards
// ---------------------------------------------------------------------------

function isBflSubmitResponse(val: unknown): val is { id: string } {
  return (
    typeof val === 'object' &&
    val !== null &&
    typeof (val as Record<string, unknown>).id === 'string'
  );
}

function isBflPollResponse(
  val: unknown,
): val is { status: string; result: { sample: string } | null } {
  if (typeof val !== 'object' || val === null) return false;
  const obj = val as Record<string, unknown>;
  if (typeof obj.status !== 'string') return false;
  if (obj.result != null) {
    if (typeof obj.result !== 'object') return false;
    if (typeof (obj.result as Record<string, unknown>).sample !== 'string') return false;
  }
  return true;
}

// ---------------------------------------------------------------------------
// FluxImageProvider
// ---------------------------------------------------------------------------

export class FluxImageProvider implements ImageProvider {
  readonly id = 'flux';

  private readonly apiKey: string;
  private readonly baseUrl: string;
  private readonly model: string;
  private readonly timeoutMs: number;
  private readonly maxPollAttempts: number;
  private readonly pollIntervalMs: number;
  private readonly observer: AIProviderObserver;
  private readonly fetchFn: typeof globalThis.fetch;
  private readonly sleepFn: (ms: number) => Promise<void>;

  constructor(config: FluxImageProviderConfig) {
    this.apiKey = config.apiKey;
    this.baseUrl = (config.baseUrl ?? DEFAULT_BASE_URL).replace(/\/$/, '');
    this.model = config.model ?? DEFAULT_MODEL;
    this.timeoutMs = config.timeoutMs ?? DEFAULT_TIMEOUT_MS;
    this.maxPollAttempts = config.maxPollAttempts ?? DEFAULT_MAX_POLL_ATTEMPTS;
    this.pollIntervalMs = config.pollIntervalMs ?? DEFAULT_POLL_INTERVAL_MS;
    this.observer = config.observer ?? new NoopAIProviderObserver();
    this.fetchFn = config.fetch ?? globalThis.fetch;
    this.sleepFn =
      config.sleep ?? ((ms: number) => new Promise((resolve) => setTimeout(resolve, ms)));
  }

  async generateFromText(request: ImageGenerationRequest): Promise<ImageGenerationResult> {
    const t0 = Date.now();

    this.observer.observe({
      provider: 'flux',
      operation: 'generateFromText',
      status: 'started',
      model: this.model,
      ...(Number.isFinite(request.width) ? { requestWidth: request.width } : {}),
      ...(Number.isFinite(request.height) ? { requestHeight: request.height } : {}),
    });

    try {
      if (!request.prompt?.trim()) {
        throw new AIProviderError({
          code: 'PROVIDER_INVALID_REQUEST',
          provider: 'flux',
          message: 'Prompt must not be empty',
        });
      }

      if (!Number.isFinite(request.width) || request.width <= 0) {
        throw new AIProviderError({
          code: 'PROVIDER_INVALID_REQUEST',
          provider: 'flux',
          message: 'Width must be a positive finite number',
        });
      }

      if (!Number.isFinite(request.height) || request.height <= 0) {
        throw new AIProviderError({
          code: 'PROVIDER_INVALID_REQUEST',
          provider: 'flux',
          message: 'Height must be a positive finite number',
        });
      }

      const warnings: string[] = [];
      if (request.transparentBackground) {
        warnings.push('transparentBackground is not supported by flux-schnell; ignoring');
      }

      const jobId = await this.submitJob(request);
      const sampleUrl = await this.pollForResult(jobId);
      const imageData = await this.fetchImageBytes(sampleUrl);

      const format = request.format ?? 'png';
      const result: ImageGenerationResult = {
        provider: 'flux',
        model: this.model,
        mimeType: `image/${format}`,
        width: request.width,
        height: request.height,
        data: imageData,
        ...(request.seed !== undefined ? { seed: request.seed } : {}),
        warnings,
        metadata: { kind: request.kind ?? 'unknown' },
      };

      this.observer.observe({
        provider: 'flux',
        operation: 'generateFromText',
        status: 'succeeded',
        durationMs: Date.now() - t0,
        model: this.model,
        requestWidth: request.width,
        requestHeight: request.height,
      });

      return result;
    } catch (err) {
      this.observer.observe({
        provider: 'flux',
        operation: 'generateFromText',
        status: 'failed',
        durationMs: Date.now() - t0,
        errorCode: err instanceof AIProviderError ? err.code : 'PROVIDER_UNAVAILABLE',
        retryable: err instanceof AIProviderError ? err.retryable : false,
      });
      throw err;
    }
  }

  async editImage(_request: ImageEditRequest): Promise<ImageGenerationResult> {
    const t0 = Date.now();
    this.observer.observe({
      provider: 'flux',
      operation: 'editImage',
      status: 'started',
      model: this.model,
    });
    this.observer.observe({
      provider: 'flux',
      operation: 'editImage',
      status: 'failed',
      durationMs: Date.now() - t0,
      errorCode: 'PROVIDER_EDIT_UNSUPPORTED',
      retryable: false,
    });
    throw new AIProviderError({
      code: 'PROVIDER_EDIT_UNSUPPORTED',
      provider: 'flux',
      message: 'FLUX does not support image-to-image edits',
      retryable: false,
    });
  }

  // -------------------------------------------------------------------------
  // Step 1: submit generation job
  // -------------------------------------------------------------------------

  private async submitJob(request: ImageGenerationRequest): Promise<string> {
    const url = `${this.baseUrl}/v1/${this.model}`;

    // Only include fields the BFL API actually supports — never log or expose values
    const body: Record<string, unknown> = {
      prompt: request.prompt,
      width: request.width,
      height: request.height,
      output_format: request.format ?? 'png',
    };
    if (request.seed !== undefined) {
      body.seed = request.seed;
    }

    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this.timeoutMs);

    let response: Response;
    try {
      response = await this.fetchFn(url, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'x-key': this.apiKey,
        },
        body: JSON.stringify(body),
        signal: controller.signal,
      });
    } catch (err) {
      clearTimeout(timer);
      if ((err as Error).name === 'AbortError') {
        throw new AIProviderError({
          code: 'PROVIDER_TIMEOUT',
          provider: 'flux',
          message: 'FLUX submit request timed out',
          retryable: true,
        });
      }
      throw new AIProviderError({
        code: 'PROVIDER_UNAVAILABLE',
        provider: 'flux',
        message: 'FLUX submit request failed: network error',
        retryable: true,
      });
    }
    clearTimeout(timer);

    if (!response.ok) {
      throw new AIProviderError({
        code: 'PROVIDER_HTTP_ERROR',
        provider: 'flux',
        message: `FLUX submit returned HTTP ${response.status}`,
        retryable: response.status >= 500,
      });
    }

    let raw: unknown;
    try {
      raw = await response.json();
    } catch {
      throw new AIProviderError({
        code: 'PROVIDER_INVALID_RESPONSE',
        provider: 'flux',
        message: 'FLUX submit response was not valid JSON',
      });
    }

    if (!isBflSubmitResponse(raw)) {
      throw new AIProviderError({
        code: 'PROVIDER_INVALID_RESPONSE',
        provider: 'flux',
        message: 'FLUX submit response did not contain a job id',
      });
    }

    return raw.id;
  }

  // -------------------------------------------------------------------------
  // Step 2: poll for job completion
  // -------------------------------------------------------------------------

  private async pollForResult(jobId: string): Promise<string> {
    const pollUrl = `${this.baseUrl}/v1/get_result?id=${encodeURIComponent(jobId)}`;

    for (let attempt = 0; attempt < this.maxPollAttempts; attempt++) {
      if (attempt > 0) {
        await this.sleepFn(this.pollIntervalMs);
      }

      let response: Response;
      try {
        response = await this.fetchFn(pollUrl, {
          method: 'GET',
          headers: { 'x-key': this.apiKey },
        });
      } catch {
        throw new AIProviderError({
          code: 'PROVIDER_UNAVAILABLE',
          provider: 'flux',
          message: 'FLUX poll request failed: network error',
          retryable: true,
        });
      }

      if (!response.ok) {
        throw new AIProviderError({
          code: 'PROVIDER_HTTP_ERROR',
          provider: 'flux',
          message: `FLUX poll returned HTTP ${response.status}`,
          retryable: response.status >= 500,
        });
      }

      let raw: unknown;
      try {
        raw = await response.json();
      } catch {
        throw new AIProviderError({
          code: 'PROVIDER_INVALID_RESPONSE',
          provider: 'flux',
          message: 'FLUX poll response was not valid JSON',
        });
      }

      if (!isBflPollResponse(raw)) {
        throw new AIProviderError({
          code: 'PROVIDER_INVALID_RESPONSE',
          provider: 'flux',
          message: 'FLUX poll response did not match expected shape',
        });
      }

      if (raw.status === 'Ready' && raw.result?.sample) {
        return raw.result.sample;
      }
      // Continue polling on Pending / Processing / other non-Ready statuses
    }

    throw new AIProviderError({
      code: 'PROVIDER_TIMEOUT',
      provider: 'flux',
      message: 'FLUX generation timed out after maximum poll attempts',
      retryable: true,
    });
  }

  // -------------------------------------------------------------------------
  // Step 3: retrieve image bytes from the temporary sample URL
  // -------------------------------------------------------------------------
  // The sample URL is a presigned temporary URL. Bytes are fetched immediately
  // and returned as Uint8Array. The URL is never stored, logged, or returned.

  private async fetchImageBytes(imageUrl: string): Promise<Uint8Array> {
    let response: Response;
    try {
      response = await this.fetchFn(imageUrl, { method: 'GET' });
    } catch {
      throw new AIProviderError({
        code: 'PROVIDER_UNAVAILABLE',
        provider: 'flux',
        message: 'Failed to fetch generated image bytes: network error',
        retryable: true,
      });
    }

    if (!response.ok) {
      throw new AIProviderError({
        code: 'PROVIDER_HTTP_ERROR',
        provider: 'flux',
        message: `Failed to retrieve image: HTTP ${response.status}`,
        retryable: response.status >= 500,
      });
    }

    try {
      const buffer = await response.arrayBuffer();
      return new Uint8Array(buffer);
    } catch {
      throw new AIProviderError({
        code: 'PROVIDER_INVALID_RESPONSE',
        provider: 'flux',
        message: 'Failed to read image response bytes',
      });
    }
  }
}
